services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /etc/letsencrypt/live/srv1023256.hstgr.cloud/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/srv1023256.hstgr.cloud/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - users-service
      - subscriptions-service
      - orders-service
      - payments-service
      - coupons-service
      - leads-service
    restart: always
    networks:
      - matheuspersonal

  users-service:
    build:
      context: ./services
      dockerfile: users/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  subscriptions-service:
    build:
      context: ./services
      dockerfile: subscriptions/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  orders-service:
    build:
      context: ./services
      dockerfile: orders/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  payments-service:
    build:
      context: ./services
      dockerfile: payments/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  coupons-service:
    build:
      context: ./services
      dockerfile: coupons/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  leads-service:
    build:
      context: ./services
      dockerfile: leads/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

networks:
  matheuspersonal:
    driver: bridge
