services:
  users-service:
    build:
      context: ./services
      dockerfile: users/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  subscriptions-service:
    build:
      context: ./services
      dockerfile: subscriptions/Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  orders-service:
    build:
      context: ./services
      dockerfile: orders/Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  payments-service:
    build:
      context: ./services
      dockerfile: payments/Dockerfile
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  coupons-service:
    build:
      context: ./services
      dockerfile: coupons/Dockerfile
    ports:
      - "8005:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

  leads-service:
    build:
      context: ./services
      dockerfile: leads/Dockerfile
    ports:
      - "8006:8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - matheuspersonal

networks:
  matheuspersonal:
    driver: bridge
