events {}

http {
    server {
        listen 80;
        server_name srv1023256.hstgr.cloud;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name srv1023256.hstgr.cloud;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers   HIGH:!aNULL:!MD5;

        location /api/users/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://users-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/subscriptions/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://subscriptions-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/orders/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://orders-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/payments/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://payments-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/coupons/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://coupons-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/leads/ {
            include /etc/nginx/cors.conf;
            proxy_pass http://leads-service:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
